spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: mi_clave_super_secreta_12345678901234567890

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/