spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/condominio_auth
    username: postgres
    password: admin
server:
  port: 8081

##url de person-service para ws
#person:
#  url: http://localhost:8080
#
##url de person-service para ws
#edificio:a
#  url: http://localhost:8082