services:
  # 🐘 Base de datos PostgreSQL
  postgres-person:
    image: postgres:16
    container_name: condominio-postgres-person
    environment:
      POSTGRES_DB: condominio_personas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - condominio_person_data:/var/lib/postgresql/data   # 💾 Persistencia
    networks:
      - ms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-auth:
    image: postgres:16
    container_name: condominio-postgres-auth
    environment:
      POSTGRES_DB: condominio_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - condominio_auth_data:/var/lib/postgresql/data   # 💾 Persistencia
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-edificio:
    image: postgres:16
    container_name: condominio-postgres-edificio
    environment:
      POSTGRES_DB: condominio_edificio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - condominio_edificio_data:/var/lib/postgresql/data   # 💾 Persistencia
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # 🚀 microservicios
  person-service:
    build: ./person-service   # 📁 Ruta donde está el Dockerfile
    container_name: condominio-person-service
    ports:
      - "8080:8080"           # 🌐 host:contenedor
    depends_on:
      postgres-person:
        condition: service_healthy  # ⛓️ Espera a que postgres arranque
      eureka-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Esto le dice que use el profile docker del yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-person:5432/condominio_personas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - ms-network
    #restart: always           # 🔄 Se reinicia si falla

  auth-service:
    build: ./auth-service   # 📁 Ruta donde está el Dockerfile
    container_name: condominio-auth-service
    ports:
      - "8081:8080"           # 🌐 host:contenedor
    depends_on:
      postgres-auth:
        condition: service_healthy  # ⛓️ Espera a que postgres arranque
      eureka-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Esto le dice que use el profile docker del yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/condominio_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - ms-network

  edificio-service:
    build: ./edificio-service   # 📁 Ruta donde está el Dockerfile
    container_name: condominio-edificio-service
    ports:
      - "8082:8080"           # 🌐 host:contenedor
    depends_on:
      postgres-edificio:
        condition: service_healthy  # ⛓️ Espera a que postgres arranque
      eureka-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Esto le dice que use el profile docker del yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-edificio:5432/condominio_edificio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - ms-network

  # Eureka-server
  eureka-server:
    build:
      context: ./eureka-server
    container_name: condominio-eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

# 💾 Volumen para no perder datos
volumes:
  condominio_person_data:
  condominio_auth_data:
  condominio_edificio_data:

# Networks
networks:
  ms-network:
    driver: bridge

