package com.condominio.persona.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    BUSINESS_ERROR,
    DATA_INTEGRITY_ERROR,
    BAD_REQUEST_ERROR,
    ERROR_SERVIDOR_ERROR,
    DATA_ALREADY_EXIST_ERROR,
    EXTERNAL_RESOURCE_ERROR,
    RUN_TIME_EXCEPTION_ERROR,
    RESOURCE_NOT_FOUND_ERROR,
    GENERAL_ERROR,
    INVALID_JSON
}
