spring:
  application:
    name: edificio-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  #activar colores para el log
  output:
    ansi:
      enabled: ALWAYS
  #Config de envío de correos
  mail:
    host: smtp.gmail.com
    port: 587
    username: essi.lcordova@gmail.com
    password: hagp yxmg aecy qdpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#config de log y crear archivo
logging:
  file:
    name: logs/edificio-service.log
  level:
    root: INFO
    com.condominio.auth: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    com.condominio.edificio.feignclient: DEBUG
    com.condominio.edificio.feignclient.SunatClientWs: DEBUG

#config de security
jwt:
  expiration: 900000
  long-expiration: 604800000
  secret: mi_clave_super_secreta_12345678901234567890

#url de reniec para ws
sunat:
  url: https://api.decolecta.com/v1/sunat/ruc/full

#token de url de reniec para ws
api:
  token: sk_15447.JV3izpDQeYgVpb3Gg3eCn1d0DAzkg8TQ

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# con las 3 lineas de abajo le decimos que levante el proyecto sin la necesidad de la cfg de bd
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#OJO, hay 2 archivos extra de configuración, uno para dev y el otro para el docker, se configura de la siguiente forma:
#Spring usa -> spring.profiles.active
#En Run Configuration -> Environment variables -> SPRING_PROFILES_ACTIVE=dev